"""Webhook signature verification, including the cross-language vector suite.

``tests/fixtures/webhook_vectors.json`` is generated by the **TypeScript**
``signWebhook`` in ``packages/core/src/webhook.ts``, executed directly with
``node --experimental-strip-types``. It is the only guard against the two
implementations drifting: cross-language agreement is proven here, not assumed.
"""

from __future__ import annotations

import json
import pathlib
import time
from typing import Any

import pytest

from dodomain import DEFAULT_TOLERANCE_MS, SIGNATURE_HEADER, verify_webhook
from dodomain.webhooks import sign_webhook

VECTORS_PATH = pathlib.Path(__file__).parent / "fixtures" / "webhook_vectors.json"
VECTORS: list[dict[str, Any]] = json.loads(VECTORS_PATH.read_text(encoding="utf-8"))["vectors"]

SECRET = "whsec_test_0123456789abcdef"
BODY = '{"event":"connection.verified","data":{"domain":"app.customer.com"}}'
NOW_MS = 1786000000000


def _header(**overrides: Any) -> str:
    timestamp = overrides.pop("timestamp_ms", NOW_MS)
    return sign_webhook(overrides.pop("secret", SECRET), overrides.pop("body", BODY), timestamp)


def test_the_signature_header_name_is_the_one_doDomain_sends() -> None:
    assert SIGNATURE_HEADER == "x-dodomain-signature"


def test_the_default_replay_window_is_five_minutes() -> None:
    assert DEFAULT_TOLERANCE_MS == 5 * 60 * 1000


@pytest.mark.parametrize("vector", VECTORS, ids=[v["name"] for v in VECTORS])
def test_every_signature_the_typescript_sdk_produces_verifies_in_python(
    vector: dict[str, Any],
) -> None:
    assert (
        verify_webhook(
            vector["secret"],
            vector["body"],
            vector["header"],
            now_ms=vector["timestamp_ms"],
        )
        is True
    )


@pytest.mark.parametrize("vector", VECTORS, ids=[v["name"] for v in VECTORS])
def test_python_reproduces_the_typescript_signature_byte_for_byte(vector: dict[str, Any]) -> None:
    assert (
        sign_webhook(vector["secret"], vector["body"], vector["timestamp_ms"]) == vector["header"]
    )


@pytest.mark.parametrize("vector", VECTORS, ids=[v["name"] for v in VECTORS])
def test_a_typescript_signature_fails_against_a_tampered_body(vector: dict[str, Any]) -> None:
    assert (
        verify_webhook(
            vector["secret"],
            vector["body"] + " ",
            vector["header"],
            now_ms=vector["timestamp_ms"],
        )
        is False
    )


def test_a_valid_signature_verifies() -> None:
    assert verify_webhook(SECRET, BODY, _header(), now_ms=NOW_MS) is True


def test_the_raw_body_may_be_bytes() -> None:
    assert verify_webhook(SECRET, BODY.encode(), _header(), now_ms=NOW_MS) is True


def test_the_secret_may_be_bytes() -> None:
    assert verify_webhook(SECRET.encode(), BODY, _header(), now_ms=NOW_MS) is True


def test_the_wrong_secret_fails() -> None:
    assert verify_webhook("whsec_other", BODY, _header(), now_ms=NOW_MS) is False


def test_a_tampered_body_fails() -> None:
    assert verify_webhook(SECRET, BODY.replace("verified", "failed"), _header(), now_ms=NOW_MS) is (
        False
    )


def test_a_timestamp_older_than_the_window_fails() -> None:
    stale = _header(timestamp_ms=NOW_MS - DEFAULT_TOLERANCE_MS - 1)
    assert verify_webhook(SECRET, BODY, stale, now_ms=NOW_MS) is False


def test_a_timestamp_from_the_future_beyond_the_window_also_fails() -> None:
    ahead = _header(timestamp_ms=NOW_MS + DEFAULT_TOLERANCE_MS + 1)
    assert verify_webhook(SECRET, BODY, ahead, now_ms=NOW_MS) is False


def test_a_timestamp_at_the_edge_of_the_window_still_verifies() -> None:
    edge = _header(timestamp_ms=NOW_MS - DEFAULT_TOLERANCE_MS)
    assert verify_webhook(SECRET, BODY, edge, now_ms=NOW_MS) is True


def test_a_custom_tolerance_is_honoured() -> None:
    old = _header(timestamp_ms=NOW_MS - 600_000)
    assert verify_webhook(SECRET, BODY, old, now_ms=NOW_MS) is False
    assert verify_webhook(SECRET, BODY, old, tolerance_ms=900_000, now_ms=NOW_MS) is True


def test_now_ms_defaults_to_the_real_clock() -> None:
    header = sign_webhook(SECRET, BODY, int(time.time() * 1000))
    assert verify_webhook(SECRET, BODY, header) is True


# ── the shape gate: a crafted header is a False, never an exception ─────────


@pytest.mark.parametrize(
    ("label", "header"),
    [
        ("non-hex v1", f"t={NOW_MS},v1=" + "z" * 64),
        ("uppercase hex v1", f"t={NOW_MS},v1=" + "A" * 64),
        ("64 chars with a multi-byte codepoint", f"t={NOW_MS},v1=" + "é" * 64),
        ("64 chars of emoji", f"t={NOW_MS},v1=" + "🎉" * 64),
        ("v1 too short", f"t={NOW_MS},v1=" + "a" * 63),
        ("v1 too long", f"t={NOW_MS},v1=" + "a" * 65),
        ("v1 missing", f"t={NOW_MS}"),
        ("v1 empty", f"t={NOW_MS},v1="),
        ("t missing", "v1=" + "a" * 64),
        ("t empty", f"t=,v1={'a' * 64}"),
        ("t not a number", f"t=yesterday,v1={'a' * 64}"),
        ("t negative", f"t=-5,v1={'a' * 64}"),
        ("t zero", f"t=0,v1={'a' * 64}"),
        ("t is a float", f"t=1786000000000.5,v1={'a' * 64}"),
        ("empty header", ""),
        ("garbage header", "not-even-close"),
        ("only commas", ",,,"),
        ("sql-ish injection", "t=1' OR '1'='1,v1=x"),
        ("null bytes", "t=\x00,v1=\x00"),
        ("very long header", "t=1," + "v1=a" * 400),
    ],
)
def test_a_malformed_signature_header_returns_false_and_never_raises(
    label: str, header: str
) -> None:
    # A 64-CHARACTER v1 holding a multi-byte codepoint is the load-bearing case:
    # unshaped, hex decoding raises and turns an attacker-controlled header into
    # a 500 inside the integrator's handler. A malformed signature is a failed
    # verification, not an error.
    assert verify_webhook(SECRET, BODY, header, now_ms=NOW_MS) is False, label


@pytest.mark.parametrize("header", [None, 12345, b"t=1,v1=x", ["t=1"], {"t": 1}])
def test_a_non_string_header_returns_false(header: Any) -> None:
    assert verify_webhook(SECRET, BODY, header, now_ms=NOW_MS) is False


def test_a_non_string_body_returns_false_rather_than_raising() -> None:
    assert verify_webhook(SECRET, {"not": "raw"}, _header(), now_ms=NOW_MS) is False


def test_extra_header_fields_are_tolerated() -> None:
    header = f"{_header()},v0=legacy,scheme=hmac-sha256"
    assert verify_webhook(SECRET, BODY, header, now_ms=NOW_MS) is True


def test_whitespace_around_header_fields_is_tolerated() -> None:
    parts = _header().split(",")
    header = " , ".join(part.replace("=", " = ", 1) for part in parts)
    assert verify_webhook(SECRET, BODY, header, now_ms=NOW_MS) is True


def test_a_signature_for_a_different_timestamp_fails() -> None:
    header = f"t={NOW_MS},v1={sign_webhook(SECRET, BODY, NOW_MS + 1).split('v1=')[1]}"
    assert verify_webhook(SECRET, BODY, header, now_ms=NOW_MS) is False


def test_verification_uses_a_constant_time_comparison() -> None:
    import inspect

    import dodomain.webhooks as webhooks_module

    source = inspect.getsource(webhooks_module.verify_webhook)
    assert "hmac.compare_digest" in source
    assert "==" not in source.split("compare_digest")[0].split("expected =")[-1]
